- .gitignore
- src/modules/students/dtos/create-student.dto.ts
- src/modules/students/dtos/update-system.dto.ts
> [FIX] 학생 등록 시 논문 제목을 필수로 입력하지 않도록 수정

- README.md
> [FIX] typo #95

- src/modules/students/students.controller.ts
- src/modules/students/students.service.ts
작성자: @hynseok 
- 학생 전체 삭제 추가
- 코드 복붙했습니다
> [FEAT] 학생 전체 삭제 추가

- src/modules/reviews/reviews.service.ts
작성자: @hynseok 
- 서명 파일 없을때 예외처리 했습니다. 이렇게 하면 될지는 모르겠네요..ㅠㅠ
> [FIX] 서명 파일 없을때 예외처리

- src/modules/reviews/reviews.service.ts
작성자: @hynseok 
- 최종심사결과보고서 학과 정보가 replacer에 없어서 생기는 오류를 수정했습니다.
> [FIX] 최종심사결과보고서 학과 정보 누락 수정

- src/modules/professors/professors.service.ts
작성자: @R3gardless 
- 현재 transaction 으로 묶여 있던 로직을 `upsert` 를 사용하여 멱등성을 보장하는 로직으로 변경하였습니다.
- prisma 에서 `upsertMany` 를 지원해주지 않아 매 iteration 마다 비즈니스 로직을 수행하다보니 굉장히 느립니다... (Excel parsing 부분 제외하고 단순 비즈니스 로직 처리에 대한 실행시간 측정)
close #109
> [FIX] Implement professor bulk insert logic

- src/modules/reviews/reviews.service.ts
> [FIX] 심사결과보고서 수정

- resources/format/심사결과보고서_양식.html
- resources/format/심사보고서_양식.html
- resources/format/예비심사결과보고서_양식.html
- resources/format/예비심사보고서_양식.html
- src/modules/reviews/dtos/review.dto.ts
작성자: @hynseok 
3번 논문 심사 결과보고서 서식 수정
9번 [교수] 최종판정_심사의견 입력 시에는 해당 화면에서 심사의견 확인 가능하도록 수정
> [HOTFIX] 심사의견 양식 수정  /  최종판정 심사의견 확인 가능하도록 수정

- src/modules/reviews/reviews.service.ts
작성자: @hynseok 
- (13번) 심사현황 조회 api 심사가 끝난 정보도 보여지도록 수정하였습니다.
> [FIX] 심사현황 조회 심사가 끝난 정보 남기도록 수정

- src/modules/reviews/reviews.service.ts
작성자: @jcy0308 
- [교수] 학생의 논문제출이 완료되지 않은경우 심사를 할 수 없게됩니다.
- [최종심사원] 교수들의 심사가 완료되지 않은경우 심사를 할 수 없게됩니다.
- 참고 사항을 적어주세요. 코드 리뷰하는 사람이 참고해야 하는 내용을 자유로운 형식으로 적을 수 있습니다.
resolve #123
> fix: 심사논문 관련 추가 수정

- src/modules/students/students.service.ts
- src/modules/theses/theses.service.ts
작성자: @yesjuhee 
- 논문 정보를 수정할 때 수정지시사항 미반영 학과 학생의 예외 처리가 안되있는 부분을 수정했습니다.
close #126
> [FIX] 특정 학과 학생 논문 정보 업데이트 오류 수정

- resources/format/심사결과보고서_양식.html
- resources/format/심사보고서_양식.html
- resources/format/예비심사결과보고서_양식.html
- resources/format/예비심사보고서_양식.html
- src/modules/reviews/dtos/review.dto.ts
- src/modules/reviews/reviews.service.ts
- src/modules/students/students.service.ts
- src/modules/theses/theses.service.ts
> qa 배포를 위해 머지합니다.

- prisma/schema.prisma
- src/modules/achievements/achievements.controller.ts
작성자: @hynseok 
- 스키마에 논문제목 길이가 100으로 되어있어서 255로 수정하였습니다.
- 수정 권한을 관리자에게도 추가하였습니다.
- 참고 사항을 적어주세요. 코드 리뷰하는 사람이 참고해야 하는 내용을 자유로운 형식으로 적을 수 있습니다.
> [FIX] achievement 등록 오류 해결

- src/modules/reviews/reviews.service.ts
작성자: @hynseok 
- 예비심사 최종결과보고서에 서명파일 추가하는 로직이 빠져있어서 수정했습니다.
> [FIX] 최종심사보고서 예심 서명 누락 수정

- prisma/schema.prisma
- src/modules/achievements/achievements.controller.ts
- src/modules/achievements/achievements.service.ts
> [FIX] 연구실적 수정가능하도록 변경

- src/modules/reviews/dtos/get-review-final.res.dto.ts
작성자: @R3gardless 
- src/modules/reviews/dtos/get-review-final.res.dto.ts 에 있는 dto 에 title 누락 부분 추가
- dto 로직 수정 이외에는 별도로 수정한 부분 X
fix #139
> [FIX] 최종판정 제목 미표기 문제 해결

- src/modules/reviews/reviews.service.ts
작성자: @R3gardless 
- 현재 사이트에 뜨는 Review List 와 Excel 다운로드 시 나오는 Review List 가 맞지 않음
- 또한 수정 단계에 있는 학생들이 표시되지 않는 오류 해결(행정실 요구 사항)
- 학번 추가 및 심사 결과 교수 별로 다른 셀에 위치하게 분리(행정실 요구 사항)
- 심사 현황에서 수정 단계에 있는 학생들이 표시되는 부분은 행정실 요구사항입니다.
close #141
> feat: review list 내용 변경

- src/modules/achievements/achievements.service.ts
작성자: @hynseok 
- ISSN 미입력시 미제출 표시에서 빈칸으로 표시하도록 수정
> [FIX] ISSN 미입력시 미제출 표시에서 빈칸으로 표시하도록 수정

- src/modules/reviews/dtos/get-review-final-list.res.dto.ts
- src/modules/reviews/dtos/get-review-final.res.dto.ts
- src/modules/reviews/dtos/get-review-list.res.dto.ts
- src/modules/reviews/dtos/get-review.res.dto.ts
- src/modules/reviews/dtos/review.dto.ts
- src/modules/reviews/reviews.service.ts
작성자: @hynseok 
- 교수 심사현황/심사결과 api 자신의 심사역할 데이터 추가
.
close/resolve/fix #145
> [FIX] 교수 심사현황/심사결과 api 자신의 심사역할 데이터 추가

- src/modules/reviews/reviews.service.ts
> [hotfix] 심사결과보고서 심사 결과 반영

- src/modules/reviews/dtos/search-review.req.dto.ts
- src/modules/reviews/reviews.service.ts
작성자: @hynseok
- 교수 심사목록조회 조건절 날짜로 필터링하도록 수정
.
> [FIX] 교수 심사목록조회 조건절 날짜로 필터링하도록 수정

- src/modules/phases/phases.controller.ts
작성자: @hynseok
- 시스템 단계 조회 박사과정 권한 추가
> [FIX] 시스템 단계 조회 박사과정 권한 추가

- src/modules/task/task.service.ts
작성자: @hynseok
- 더미 크론잡 추가하여 금학기 기간 설정 적용
> [FIX] 더미 크론잡 추가하여 금학기 기간 설정 적용

- src/modules/students/students.service.ts
작성자: @hynseok 
- 본심 전환 process 테이블 쿼리 수정
> [FIX] 본심 전환 process 테이블 쿼리 수정

- src/modules/reviews/reviews.service.ts
작성자: @hynseok 
- 최종심사 가능 조건을 [모든 심사 완료] -> [합격이 과반수 이상일때는 심사 가능 / 과반수 미만이면 모두 심사 완료] 으로 수정했습니다.
.
> [FIX] 최종심사 가능 조건 변경

- src/modules/students/students.service.ts
작성자: @yesjuhee 
- close #162 
- 학생 등록 과정에서 Review를 생성할 때 구두심사 통과 여부 설정에 오류 발견 -> 수정
- 이미 잘못 등록된 유저들에 대해서는 DB 직접 수정하겠습니다
> [FIX] 구두 심사 결과 오류 수정
